### ISSUE TITLE
No module named 'utils.timefeatures'

### ISSUE THREAD

**Issue by bxdgl** [VEWOXIC/TGTSF#1]
hi, 
Thanks to your work, your project may be missing some files and fail to run

**Comment by VEWOXIC** [comment]
Hi,
util.timefeatures is a function that widely used in the previous transformer-based methods such as autoformer. However, we do not use this function in TGTSF. Thus, we remove it. 

Would you like to provide more detail such as error log so that we can help you check the code? 

BG,
Zhijian

**Comment by VEWOXIC** [comment]
Upon checking, we find that the scripts in utils are not uploaded somehow ;(

We have fixed this issue, please pull the repo and try again! 

Thanks for your advice and sorry for the inconvenient.

**Comment by VEWOXIC** [comment]
if there is no further questions, I will close this issue. please feel free to reopen it.
