### ISSUE TITLE
No electricity dataset

### ISSUE THREAD

**Issue by QianYUHA** [VEWOXIC/TGTSF#2]
Hi! Thank you for your work.
Most datasets and scripts are clear.
But I can't find the electricity dataset you used in TGTSF.
Looking forward to your reply!

**Comment by VEWOXIC** [comment]
Sorry for the late reply. We will release the caption script ASAP. (in this week, hopefully...) Sorry for the incontinence.

**Comment by VEWOXIC** [comment]
Preparation script for elec_caption dataset is uploaded! see: [elec_caption.ipynb](https://github.com/VEWOXIC/TGTSF/blob/04f4b05467e00b9f9c7ac97d944b9a000a1af707/dataset/electricity_captioned/elec_caption.ipynb)

Please feel free to reach out if you have any problem with this.

**Comment by VEWOXIC** [comment]
If there is no further question, I will close this issue. Please feel free to reopen it.
