### ISSUE TITLE
Too many values to unpack for train_loader

### ISSUE THREAD

**Issue by QianYUHA** [VEWOXIC/TGTSF#3]
Hi!
When I tried to run the toy.sh, it seems that in exp_TGTSF.py the train_loader has received more values than it should have.
There may be some bugs in the code.

Traceback (most recent call last):
File "/run_TGTSF.py", line 180, in <module>
exp.train(setting)
File "/exp/exp_TGTSF.py", line 163, in train
for i, (batch_x, batch_y, batch_news, batch_des) in enumerate(train_loader):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4）

Looking forward to your reply!

**Comment by VEWOXIC** [comment]
Hi, thanks for reaching out. It seems that this exp-TGTSF.py is using an out-dated version of dataloader. Maybe consider add another parameter as mask? 

```python
for i, (batch_x, batch_y, batch_news, batch_des, news_mask) in enumerate(train_loader):
....
``` 

Also you may need to pass the mask to the model. 

Or you can give it a try with exp_TGTSF_date.py. 

We are still working on some improvement. And thanks again for reporting this issue.

**Comment by VEWOXIC** [comment]
If there is no further question, I will close this issue. Please feel free to reopen it.
